### ISSUE TITLE
Brand new to github actions, probably am doing something wrong

### ISSUE THREAD

**Issue by Trevoke** [jsumners/gh-action-hugo-deploy#1]
So .. Here's what I have:

https://github.com/tales-of-a-wandering-software-maker/site-src/runs/1000792074

> fatal: repository 'https://github.com/tales-of-a-wandering-softare-maker/tales-of-a-wandering-softare-maker.github.io.git/' not found

Buuuut https://github.com/tales-of-a-wandering-software-maker/tales-of-a-wandering-softare-maker.github.io ?

**Comment by jsumners** [comment]
Does the token have "repo" permissions?

**Comment by Trevoke** [comment]
Here is what I selected: 
![image](https://user-images.githubusercontent.com/67913/90581372-0c402e00-e199-11ea-85d1-2e5e5dd120e7.png)

This is:

1. a personal token
2. on this github account
3. which is the owner of the tales-of-a-wandering-software-maker org

This token is also set as `DEPLOY_TOKEN` on `site-src`. I set it as `Deploy_Token` when I created it but it looks like Github may have upper-cased it.

![image](https://user-images.githubusercontent.com/67913/90581448-41e51700-e199-11ea-8fd4-3c705c375583.png)

**Comment by jsumners** [comment]
The name doesn't matter as long as it is referenced correctly in the workflow yaml. Try using the all upper case name in your yaml file.

**Comment by Trevoke** [comment]
Alright - https://github.com/tales-of-a-wandering-software-maker/site-src/blob/master/.github/workflows/main.yml

No dice :(

https://github.com/tales-of-a-wandering-software-maker/site-src/runs/1001032727?check_suite_focus=true

**Comment by Trevoke** [comment]
I also generated a new token (with the same permissions as above, still on this account) and updated the secret value, in case that was the problem, but nope.

Did something change within Github or something?

**Comment by Trevoke** [comment]
I switched over to https://github.com/marketplace/actions/hugo-setup

So I no longer need this figured out; sorry for taking up your time.
